# Generated by Django 3.2.18 on 2023-03-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
