# Generated by Django 3.2.18 on 2023-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodapp', '0002_remove_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Project'), (1, 'Post')], default=0),
        ),
    ]
